### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ykcab** [rfjakob/eme#5]
There are a number of dead links, will you ever consider fixing them?
- http://grouper.ieee.org/groups/1619/email/msg00310.html
- http://grouper.ieee.org/groups/1619/email/pdf00020.pdf
- http://grouper.ieee.org/groups/1619/email/msg00218.html
- http://grouper.ieee.org/groups/1619/email-2/msg00005.html

For _IEEE P1619.2™/D9 Draft Standard for Wide-Block Encryption for Shared Storage Media_, maybe use this link [https://ieeexplore.ieee.org/document/5729263](https://ieeexplore.ieee.org/document/5729263)

**Comment by rfjakob** [comment]
Oh dear, they deleted the whole mailing list archive. But everything seems to be archived at http://web.archive.org/ .
